spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    driver-class-name: org.h2.Driver
    password:
    username: sa
    url: jdbc:h2:tcp://localhost/~/usedmarket

logging:
  level:
    org.hibernate.SQL: debug

file.dir: /Users/kisnahc/Desktop/used-market-img/

