spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: debug

file.dir: /Users/kisnahc/Desktop/used-market-img/

